[pytest]
addopts = -s -p no:warnings --color=yes --alluredir ../report/report_result --clean-alluredir
env = test
switch_domain = partner
testpaths = ../scripts
python_files = test_partner.py
python_classes = Test*
python_functions = test*


