[pytest]
disable_test_id_escaping_and_forfeit_all_rights_to_community_support = True
addopts = -s -p no:warnings --color=yes --alluredir ../report/report_result --clean-alluredir
env = test
switch_domain = ysb,partner
testpaths = ../scripts
python_files = test_partner.py
python_classes = Test*
python_functions = test*


