---
'test_environment':
  'DBConnection':
    'charset': 'utf8'
    'database': 'api_report'
    'host': '10.14.2.245'
    'password': '123456'
    'port': '3306'
    'user': 'root'
  'session':
  - 'domain': 'oa'
    'host': 'oasd.lianlianlvyou.com'
    'password': '1'
    'port': '443'
    'protocol': 'https://'
    'username': '13550087714'
  - 'domain': 'ysb'
    'host': 'pre-server-app-business.lianlianlvyou.com'
    'password': '123456'
    'port': '443'
    'protocol': 'https://'
    'username': '13550087714'
  - 'domain': 'partner'
    'host': 'partner.llzby.top'
    'password': '123456'
    'port': '443'
    'protocol': 'https://'
    'username': '13550086666'
...
---
'dev_environment':
  'DBConnection':
    'charset': 'utf8'
    'database': 'nearby_travel'
    'host': 'pc-2ze8c757mjh350kql-public.rwlb.rds.aliyuncs.com'
    'password': 'LLdev#2022zby'
    'port': '3306'
    'user': 'lldb_dev'
  'session':
  - 'domain': 'oa'
    'host': 'oasd.lianlianlvyou.com'
    'password': '1'
    'port': '443'
    'protocol': 'https://'
    'username': '13550087714'
  - 'domain': 'ysb'
    'host': 'pre-server-app-business.lianlianlvyou.com'
    'password': '123456'
    'port': '443'
    'protocol': 'https://'
    'username': '13550087714'
  - 'domain': 'partner'
    'host': 'partner.llzby.top'
    'password': '123456'
    'port': '443'
    'protocol': 'https://'
    'username': '13550088888'
...
---
'pro_environment':
  'DBConnection':
    'charset': 'utf8'
    'database': 'nearby_travel'
    'host': 'pc-2ze8c757mjh350kql-public.rwlb.rds.aliyuncs.com'
    'password': 'LLdev#2022zby'
    'port': '3306'
    'user': 'lldb_dev'
  'session':
  - 'domain': 'oa'
    'host': 'oasd.lianlianlvyou.com'
    'password': '1'
    'port': '443'
    'protocol': 'https://'
    'username': '13550087714'
  - 'domain': 'ysb'
    'host': 'pre-server-app-business.lianlianlvyou.com'
    'password': '123456'
    'port': '443'
    'protocol': 'https://'
    'username': '13550087714'
  - 'domain': 'partner'
    'host': 'partner.llzby.top'
    'password': '123456'
    'port': '443'
    'protocol': 'https://'
    'username': '13550088888'
...
